[project]
name = "cargo-orchestrator"
version = "0.1.0"
description = "A Python library for running cargo build and parsing its output"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]